name: xAuth
version: '${project.version}'
main: com.xauth.xAuth
api-version: 1.19
commands:
  xauth:
    description: Open the login GUI or reload the config
    usage: /xauth <reload|debug>
    permission: xauth.use

permissions:
  xauth.use:
    description: Allows players to use the /xauth command
    default: true