name: xAuth
version: '${project.version}'
main: com.xauth.xAuth
api-version: 1.19
commands:
  xauth:
    description: Opens the login GUI
    usage: /xauth [reload]
permissions:
  xauth.reload:
    description: Allows reloading the plugin configuration
    default: op